server:
   port: 8101
# JSON Pretty Print
spring:
    jackson:
       serialization:
          indent_output: true
    main:
       banner-mode: "off"
    datasource:
       url: jdbc:h2:file:/home/pnichols/data/recovery-2.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
       driverClassName: org.h2.Driver
       username: sa
       password: 
       platform: h2
    h2:
      console:
         enabled: true
         path: /console 
sender:
   endpoint: http://localhost:8101/api/reactiveservice/receivemessage
   
       
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.clc.reactive: DEBUG
  file: logs/reactive-service-receiver.log
  